# Generated by Django 6.0.1 on 2026-01-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('astronaut', 'Astronaut'), ('guitarist', 'Guitarist'), ('book_worm', 'Book Worm'), ('original', 'Original')], default='original', max_length=32),
        ),
    ]
